services:
  db:
    image: mysql:8.0
    container_name: sceneit_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sceneit
      MYSQL_USER: g14
      MYSQL_PASSWORD: g14
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d

  app:
    build: .
    container_name: sceneit_app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/sceneit?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: g14
      SPRING_DATASOURCE_PASSWORD: g14

volumes:
  db_data:
